version: '3'

services:

  database:
    image: postgres
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=somedatabasepassword
      - POSTGRES_DB=miilog
    volumes:
      - ./data-postgres:/var/lib/postgresql/data

  dashboard:
    image: metabase/metabase
    depends_on:
      - "database"
    ports:
      - 5000:3000
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
      - JAVA_TIMEZONE="Asia/Kuala Lumpur"
    volumes:
      - ./data-metabase:/metabase-data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "database"
    environment:
      - PG_USER=app
      - PG_PASSWORD=somedatabasepassword
      - PG_SERVER=database
      - PG_DATABASE=miilog
      - DEVICE_NAME=Office
      - DEVICE_ADDR=192.168.1.217
      - APP_INTERVAL=60000
